### ISSUE TITLE
MissingPointerError: Token "relationshipLinks" does not exist.\n

### ISSUE THREAD

**Issue by Floo0S** [bluewire-solutions/shopware-6-api-client#3] opened 2021-05-07 14:04 UTC
After upgrading to Shopware 6.4 this client stops working.
Although I have changed the URL API Path to new path without version "api/_info/openapi3.json"

**Comment by sydetion** [comment] 2021-05-07 14:05
oh good to know - will check asap!

**Comment by sydetion** [comment] 2021-05-22 08:29
our common use cases still work. can you provide the line of code causing the issue @Floo0S ?

**Comment by sydetion** [comment] 2021-05-22 14:05
o.k. could be reproduced now - seems to be an error in shopwares openapi spec

**Comment by bluewire-solutions** [comment] 2021-05-22 14:47
fixed in c68a5dd3f8c65384626dd04f0fe1316aaba3e5cd by a hotfix until shopware resolves spec issue

**Closed as completed by bluewire-solutions** 2021-05-22 14:47 UTC
